### ISSUE TITLE
Suppress warning syntax

### ISSUE THREAD

**Issue by h-ngo** [mwz/sonar-scala#103]
Hello. Does this plugin use a different syntax to suppress warning? we tried "// scalastyle:off <rule id>" and "// scalastyle:ignore <rule id>", but none seems to work.

**Comment by mwz** [comment]
scalastyle:off/on and scalastyle:ignore should work just fine, we even have a few examples of using ignore in the source code https://github.com/mwz/sonar-scala/blob/1a117a82756c9d621d8747731f16b2cd7d255870/src/main/scala/com/mwz/sonar/scala/sensor/ScalaSensor.scala#L46.

Are you sure you're applying this to Scalastyle issues? Scapegoat has a different mechanism for disabling issues.

**Comment by h-ngo** [comment]
Thanks. It works now. We messed up the rule id which we created from template.
