### ISSUE TITLE
Can findbugs support be incorporated in this plugin

### ISSUE THREAD

**Issue by Rajshr** [mwz/sonar-scala#104]
This plugin has support for Scalastyle and Scapegoat for static analysis.Any plan to include the support for Findbugs for scala

**Comment by BalmungSan** [comment]
Hi @Rajshr, thanks for the suggestion.

I haven't used it, but I just gave it a quick look, and since the SBT plugin can generate reports in xml format, it should be straightforward to support it. However we still need to check how can we create a rules repository for it.

**Comment by mwz** [comment]
I was under the impression that Findbugs is focused on Java and is not designed to analyse Scala code, therefore, most of the rules are inapplicable to Scala.

@Rajshr, do you have any examples of using it in a Scala project? Do you know if it contains any Scala specific rules? Are you interested in any particular rules that you would like this plugin to support?

**Comment by Rajshr** [comment]
Thanks @BalmungSan and @mwz for your response.I was doing an analysis on SA tools suitable for scala language and publish the result to Sonarqube when I stumbled upon this great plugin.Just out of curiosity wanted to check if there is any specific reason for Scalasytle and Scapegoat tools being used in this plugin but after analysing a bit I got the idea that Findbugs is not that great tool for Scala language.

Thanks!
