### ISSUE TITLE
Issue while pushing aggregated scoverage report to Sonarqube

### ISSUE THREAD

**Issue by Rajshr** [mwz/sonar-scala#106]
Hi @mwz ,

I am using ` sbt clean coverage test coverageReport coverageAggregate ` command  to get the combined report for all the multi-modules and then publish it to Sonarqube.I am able to get the aggregated report , but facing issue while pushing to Sonar.
Below is the snapshot of coverage in sonarqube.Is there any existing issue with the current plugin to publish the aggregated coverage report as overall coverage % is not coming up?

![image](https://user-images.githubusercontent.com/17492686/44909876-abff1a00-ad3e-11e8-873c-0c4fe91887d6.png)

**Comment by mwz** [comment]
Hi @Rajshr, if you set it up correctly, `sonar-scanner` will publish the coverage report from each module individually instead of the aggregate report, so you should not be executing the `coverageAggregate` task.

**Comment by Rajshr** [comment]
Hi @mwz , 

My current project structure is as following 
module1
   -src/main/scala
   -target\scala-2.12\scoverage-report
module2
   -src/main/scala
   -target\scala-2.12\scoverage-report

So giving , report path as 
` sonar.scala.scoverage.reportPath=target/scala-2.12/scoverage-report/scoverage.xml `  gives error as '` ` target/scala-2.12/scoverage-report/scoverage.xml (No such file or directory) `  even ` sonar.scala.scoverage.reportPath=**/target/scala-2.12/scoverage-report/scoverage.xml `  doesn't help.

Any help would be much appreciated.

Thanks!

**Comment by BalmungSan** [comment]
Hello @Rajshr 

You need to [configure the Sonar Scanner for a multi-module project](https://docs.sonarqube.org/display/SCAN/Advanced+SonarQube+Scanner+Usages). You can find an example [here](https://github.com/mwz/sonar-scala/blob/master/examples/sbt/multi-module/sonar-project.properties).

Hope it helped.

**Comment by mwz** [comment]
The easiest thing would be to just rely on the default report location, which is `target/scala-${sonar.scala.version}/scoverage-report/scoverage.xml`. If you set the `sonar.scala.version` property (e.g. to `2.12`) and leave the `sonar.scala.scoverage.reportPath` unset sonar-scala will use the default value for each of your submodules, which should work for you.

> Thanks for your response , would see if my team can contribute to enhance that support in this plugin :)

Thanks, that would be great - we're always more than happy to accept PRs from the community.

**Comment by Rajshr** [comment]
Thanks @mwz , I would try and update you on this.

**Comment by Rajshr** [comment]
Hi @mwz ,

I tried the approach mentioned by you as
 ` sonar.scala.scoverage.reportPath=
  sonar.scala.version=2.12 ` but got below error , 

Sensor Scoverage Sensor [scala]
 [scoverage] Initializing the scoverage sensor.
 [scoverage] Loading the scoverage report file: 'target/scala-2.12/scoverage-report/scoverage.xml'.
ERROR - [scoverage] Aborting the scoverage sensor execution, cause: an error occurred while reading the scoverage report file: 'target/scala-2.12/scoverage-report/scoverage.xml', the error was: target/scala-2.12/scoverage-report/scoverage.xml (No such file or directory).
- Sensor Scoverage Sensor [scala] (done) | time=13ms


Could you please guide how can that support be integrated and which class do we need to look for.

Thanks in advance !

**Comment by BalmungSan** [comment]
Hello @Rajshr,

Did you setup the `sonar.modules` property?
The idea is that you don't have to setup the `sonar.scala.scoverage.reportPath` property for each module, but you still need to tell sonar which modules are there. This is more a sonar limitation than ours.

Or we could work on an alternative [Scoverage Sensor](https://github.com/mwz/sonar-scala/blob/master/src/main/scala/com/mwz/sonar/scala/scoverage/ScoverageSensor.scala) that works on the whole project using the aggregated report.

@mwz, thoughts?

**Comment by BalmungSan** [comment]
Hi @Rajshr,

Any of them should work. Also, you don't have to leave the `sonar.scala.scoverage.reportPath` empty, just don't add it. For example:
sonar.scala.version=2.12
sonar.modules=module1, module2
Should be sufficient.

**Comment by mwz** [comment]
Also if you're using [sbt-sonar](https://github.com/mwz/sbt-sonar), you don't even need to set the `sonar.scala.version` property as this is done automatically in the latest version.

**Comment by BalmungSan** [comment]
Hey @mwz, I have an idea, but I don't know how difficult it can be, but could sbt-sonar generate the list of sonar modules automatically?

**Comment by Rajshr** [comment]
Thanks @BalmungSan and @mwz for your response.
The sonar.modules didn't help as we have a 2 levels of hierarchy inside sub modules and since we have in house sonar plugin we can't use the sbt-sonar :(

Just one last thing , can we pass comma separated values in the report path as, 
` sonar.scala.scoverage.reportPath=module1/target/scala-2.12/scoverage-report/scoverage.xml,module2/target/scala-2.12/scoverage-report/scoverage.xml `

**Comment by BalmungSan** [comment]
Hi @Rajshr,

> "As we have a 2 levels of hierarchy inside sub modules and since we have in house sonar plugin we can't use the sbt-sonar".

Uhm... that's a shame...
Well you could specify the `projectBaseDir` property of each module _([example](https://docs.sonarqube.org/display/SCAN/Advanced+SonarQube+Scanner+Usages))_, however that will be as tedious as the the first problem...

I can only think in two solutions:
+ Make an script to generate the `sonar.properties` file.
+ Or, as I said before, create an alternative **ScoverageSensor** that works on the aggregate report. _(we would be more than happy if you could help us with this @Rajshr)_

> "Just one last thing , can we pass comma separated values in the report path".

No, at the moment the property only accept one value. And even if it could accept multiple values, it won't solve your problem because the sensor is configured to run for each module.

@mwz any other ideas?

**Comment by mwz** [comment]
> Well you could specify the projectBaseDir property of each module (example), however that will be as tedious as the the first problem...

As far as I'm aware if you define the `projectBaseDir`, all of your modules will inherit this property, so it's definitely worth giving that a try.

> Or, as I said before, create an alternative ScoverageSensor that works on the aggregate report

I'm not entirely sure if it's a good idea to have one sensor which runs on the aggregated report while the other sensors (e.g. Scapegoat) still need to run on individual modules to collect the issues. That might potentially be even more confusing for someone who tries to get their setup right for the first time.

**Comment by BalmungSan** [comment]
Well, what I really mean with an alternative sensor, is one that is disabled by default. And when activated it should disable the module sensor.

Also we could make something similar for Scapegoat & Scalastyle, since they probably will have the same problem.

I know it may be confusing for beginners, but that's why it should be disabled by default.

**Comment by BalmungSan** [comment]
@Rajshr 😄 

@mwz, Well I don't really want to explore it, it was more an idea for supporting projects with many sub modules in which their teams would preffer to run aggregated analysis. So, I'm happy with either letting it die or with creating a separate issue for future work/discussion.

**Comment by Rajshr** [comment]
@mwz , Yes you can close the issue !
