### ISSUE TITLE
The file has no scoverage information associated with it in single-module grade project

### ISSUE THREAD

**Issue by barrti** [mwz/sonar-scala#109]
Hello.

I have a single-module gradle project, and while running on Jenkins reportScoverage and then sonarqube tasks I receive output like:
`The file 'src/main/scala/com/sample/utils/DatabaseReader.scala' has no scoverage information associated with it.`
It is the same for all files. The filenames are matching ones in scoverage report.

I have following configuration:
```
sonarqube {
    properties {
        property "sonar.sources", "src/main/scala"
        property "sonar.scala.version", "2.11.12"
        property "sonar.scala.scoverage.reportPath", "$buildDir/reports/scoverage/scoverage.xml"
    }
}
```

I tried to set it up locally and everything was working correctly.

Do you have any ideas what could be wrong here?

**Comment by mwz** [comment]
Hi @barrti, is your Jenkins running on Windows by any chance?

**Comment by barrti** [comment]
No, it is Amazon Linux.

**Comment by BalmungSan** [comment]
Hi @barrti, Could you run an analysis with the Debug flag _(-X)_ and paste the output here.

I'm specially interested in the Current Working Directory.

Also, just for your information, in my office we once have a similar problem _(but with maven)_, and the root case was that the project was not in the root of the repo.

*Example:*
- RepoBaseDir:
  + Project1BaseDir:
    * pom.xml
    * src/main/scala
  + Project2BaseDir:
    * pom.xml
    * src/main/scala

That team solve their problem doing a cd to the each project base dir before executing the analysis.

**Comment by barrti** [comment]
Hello @BalmungSan, thank you for your input. You were right, there were an issue with working directory:
```
06:12:01.873 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] [scoverage] The current working directory is: '/home/ubuntu/.gradle/daemon/4.4'.
```
It is a known thing with gradle daemon, I've just run it with a flag `--no-daemon` and it started working correctly.

Thanks! :)
