### ISSUE TITLE
scoverage plugin not working

### ISSUE THREAD

**Issue by BalmungSan** [mwz/sonar-scala#13]
Hi @mwz,

As I mentioned in Sagacify/sonar-scala#8 the scoverage plugin is not working for me, I had created a dummy project to reproduce the problem. ([BalmungSan/SonarScala-Scoverage-Test](https://github.com/BalmungSan/SonarScala-Scoverage-Test)).

I scan the project using the following command in the sbt shell, _";coverageOn;clean;test;coverageReport;scapegoat;sonarScan;coverageOff"_.

But, this is what is show in the sonar web page.
![image](https://user-images.githubusercontent.com/11336950/36104538-4c97137a-0fe0-11e8-9015-af6b5618829e.png)
And there is no "coverage" measure for the project.
![image](https://user-images.githubusercontent.com/11336950/36104642-93ddc6ac-0fe0-11e8-902c-32d88c38c882.png)

**Comment by mwz** [comment]
Thanks for reporting, I'll take a look shortly.

**Comment by mwz** [comment]
It looks like you mispelled `reportPath` - you have `reportPat` instead https://github.com/BalmungSan/SonarScala-Scoverage-Test/blob/master/sonar-project.properties#L9.

**Comment by BalmungSan** [comment]
...
Indeed that was the problem, sorry for bothering you for that. Anyway thanks
