### ISSUE TITLE
Implement Github preview mode for PR decoration

### ISSUE THREAD

**Issue by mwz** [mwz/sonar-scala#133]
Given that the [sonar-github](https://github.com/SonarSource/sonar-github) plugin has been deprecated starting from SonarQube 7.2 (no longer works as of 7.4) and PR decoration feature now requires paid SonarQube Developer edition (or SonarCloud subscription) for private projects, we should implement a preview mode for sonar-scala. It's probably just a matter of time before the deprecated parameter `sonar.analysis.mode` gets removed from `sonar-scanner`, so there is not much point in developing a separate (generic) plugin for Github integration, but instead, we should implement an embedded Github preview mode for those who don't want to pay for using this feature, myself included.

**Comment by BalmungSan** [comment]
**Cool!!**
Congratulations for the hard work!
