### ISSUE TITLE
how can I skip some rules in sonarqube?

### ISSUE THREAD

**Issue by brucenan** [mwz/sonar-scala#140]
For some special rules, we want to let it be. So how I omit some rules? Thanks.

**Comment by mwz** [comment]
Hi @brucenan, there are different ways of achieving that:
- go to your quality profile and disable the rules there
- if you're using a built-in quality profile, you can copy it using SonarQube UI and then disable the rules which you don't want
- you can also ignore some rules in the code, e.g. [Scalastyle](https://github.com/scalastyle/scalastyle/blob/5c4bb3e1d6b7666c4546bbbd10c4d503455bbc9e/src/main/scala/org/scalastyle/scalariform/ScalaDocChecker.scala#L68) and [Scapegoat](https://github.com/sksamuel/sbt-scapegoat#disabling-inspections)

I hope this helps.

**Comment by h-ngo** [comment]
Hi @mwz 
ignoring rules in the code (using scalastyle:off and scalastyle:ignore) seems to be broken.

![image](https://user-images.githubusercontent.com/34242287/125682619-cce27fa7-9ce9-448b-a845-0947637eb1a6.png)

Sonar: 7.9.1 LTS
Sonar-scala: 7.9.0
(Same for sonar and sonar-scala 8.x as well)

Do you happen to have any idea? Thanks

**Comment by mwz** [comment]
> // scalastyle:off and // scalastyle:ignore do work, but not when we supply a specific rule. (rule IDs confirmed correct)

@h-ngo the id needs to match the rule id in SonarQube not scalastyle - e.g. `org.scalastyle.scalariform.ClassNamesChecker` 

![Rules](https://user-images.githubusercontent.com/1190768/125777733-99a9b97d-7de2-44c7-8823-f8dbd949dea0.png)
 
see an example in code here https://github.com/sonar-scala/sonar-scala/blob/7d151b84cb638ee47ee055bf6b6cd90d5dc93e8c/src/main/scala/com/mwz/sonar/scala/sensor/Measures.scala#L36

**Comment by h-ngo** [comment]
Thanks! that worked! wasn't aware it's been changed to SonarQube rule id instead.
