### ISSUE TITLE
Trying to run sonar but i always got that incompatibility error

### ISSUE THREAD

**Issue by manodupont** [mwz/sonar-scala#151]
```
Caused by: org.picocontainer.injectors.AbstractInjector$UnsatisfiableDependenciesException: com.mwz.sonar.scala.scalastyle.ScalastyleSensor has unsatisfied dependency 'class org.sonar.api.profiles.RulesProfile' for constructor 'public com.mwz.sonar.scala.scalastyle.ScalastyleSensor(org.sonar.api.profiles.RulesProfile,com.mwz.sonar.scala.scalastyle.ScalastyleCheckerAPI)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@614321a4:112<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@1522ed99:462<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@506b5272:52<|

```

**Comment by manodupont** [comment]
Using 

```

Scala code runner version 2.12.8 -- Copyright 2002-2018, LAMP/EPFL and Lightbend, Inc.
java version "1.8.0_192"
sbt : 1.2.8

**Comment by mwz** [comment]
Hi @manodupont, could you share which versions of sonar-scala and SonarQube you're using?

**Comment by manodupont** [comment]
```
SonarQube : Version 7.6 (build 21501)
sonar-scala-plugin-1.4.0.155.jar
sonar-scala_2.12-7.3.1-assembly.jar
```

**Comment by manodupont** [comment]
The latest of all i guess! i just installed yesterday!

**Comment by mwz** [comment]
Looks like there might have been some breaking changes either in 7.5 or 7.6. The last version of SonarQube that sonar-scala was build against is 7.4, we haven't upgraded to 7.6 yet.

**Comment by manodupont** [comment]
ok! ill try downgrading.

**Comment by manodupont** [comment]
but, something i dont understand. i just run sonar-scanner. So, its locally breaking. How come SonarQube is responsible of something into that ?!

**Comment by manodupont** [comment]
I dont know the workflow between sonar-scanner and SonarQube ... so its always communicating between those twos ? I though SonarQube was just a UI to display the results ;)

**Comment by BalmungSan** [comment]
@manodupont  Not really, the workflow is something like:
The Scanner connects to the server, downloads the plugins _(and a common API that all plugins share)_, then it executes the plugin in local, and sends the results to the server.

Thus, we _(the plugins)_ depend on that common API, which is part of the server. So, if the API introduces some breaking change _(which seems is what is happening here)_, it will make the plugin fail.

The scanner itself is somewhat simple, because it is completely agnostic to what is happening.
Michael has more knowledge than me with respect to this.

**Comment by stillleben** [comment]
I stumpled upon the same issue with conflicting SonarQube 7.6.

I wanted to mention that there is now an official Scala plugin available (see https://www.sonarsource.com/products/codeanalyzers/sonarscala.html) but with quite poor abilities: No support for test coverage and a only a small number of rules. Therefore I would love to see this plugin being ported to latest SonarQube version. :-)

**Comment by manodupont** [comment]
7.4 fixed the issue!

**Comment by mwz** [comment]
Thanks for your feedback @stillleben - yes we should upgrade sonar-scala to 7.6 soon. Also, I have some nice new features in the pipeline, so stay tuned for more updates.

**Comment by mwz** [comment]
Hi @stillleben, @manodupont, just wanted to let you know that a new version of sonar-scala ([7.4](https://github.com/mwz/sonar-scala/releases/tag/v7.4.0)) with support for SonarQube 7.6 is out.
