### ISSUE TITLE
Findbugs needs sources to be compiled

### ISSUE THREAD

**Issue by yael-lorenzo-olx** [mwz/sonar-scala#153]
Please build project before executing sonar or check the location of compiled classes to make it possible for Findbugs to analyse your (sub)project (/builds/spiderman).
The situation is that I have the sources in two different folders training and service. This is the sonar-project.properties
```
sonar.projectKey=spiderman
sonar.sources=spiderman-service/src/main/scala,spiderman-training/src/main/scala
sonar.tests=spiderman-integration-tests/src/test,spiderman-training/src/test
```
Why is findbugs going to the root folder ?
how can I indicate it to go deeper?
I have tried this
```
sonar.binaries=spiderman-service/target,spiderman-training/target
```
but no luck.

I will try sonar.scala.binaries...

**Comment by yael-lorenzo-olx** [comment]
I solved like this
```
sonar.projectKey=spiderman
sonar.modules=spiderman-service,spiderman-training
module1.sonar.projectName=spiderman-service
module2.sonar.projectName=spiderman-training
sonar.language=scala
sonar.scala.version=2.11
spiderman-service.sonar.projectName=spiderman Service
spiderman-training.sonar.projectName=spiderman Training
sonar.sources=src/main/scala
sonar.tests=spiderman-integration-tests/src/test
```

**Comment by mwz** [comment]
Glad you got it sorted out.
