### ISSUE TITLE
Rule for ProcedureDefinitionChecker not found in Scalastyle repository

### ISSUE THREAD

**Issue by mwz** [mwz/sonar-scala#16]
> Rule for org.scalastyle.scalariform.ProcedureDefinitionChecker not found in Scalastyle repository! Rule won't be activated.

The correct rule is called [`ProcedureDeclarationChecker`](https://github.com/scalastyle/scalastyle/blob/master/src/main/scala/org/scalastyle/scalariform/ProcedureDeclarationChecker.scala).

**Comment by BalmungSan** [comment]
Hello, 

I had found the root of the error, it's a wrong line in the _default_config.xml_ file from the scalastyle jar, but probably you already know that.

I had open this issue, scalastyle/scalastyle#298, in the scalastyle repository, hope they fix it soon.

**Comment by mwz** [comment]
Nice, thanks for raising the issue.

**Comment by BalmungSan** [comment]
The scalastyle/scalastyle#299 PR has been merged and thus the scalastyle/scalastyle#298 Issue has been closed, for now we just have to wait for a new release of scalastyle to close this Issue.

**Comment by mwz** [comment]
Awesome, I've got Scalastyle on my watchlist, so I'll be happy to make a release as soon as a new version comes out.

**Comment by BalmungSan** [comment]
Dude, this was almost two years ago?! Wow, in my mind it was like a year ago @-@

**Comment by mwz** [comment]
wow, you're right 😱
