### ISSUE TITLE
Running on Jenkins Server without sonar-scanner binary

### ISSUE THREAD

**Issue by robbyki** [mwz/sonar-scala#207]
What is the right way to use this plugin without requiring a separate binary for sonar-scanner? Works fine on my local setup but need to be able to use a jenkins server which will run the plugin to publish coverage reports to SonarQube. Just need the coverage report xmls uploaded to SonarQube server.

**Comment by mwz** [comment]
It will be possible to execute the analysis without sonar-scanner using sbt-sonar once https://github.com/mwz/sbt-sonar/issues/19 is implemented. I'll close this issue, but feel free to add https://github.com/mwz/sbt-sonar to your watch list.
This feature should be implemented soon.
