### ISSUE TITLE
Remove all scapegoat errors

### ISSUE THREAD

**Issue by BalmungSan** [mwz/sonar-scala#21]
see discussion in #19

**Comment by BalmungSan** [comment]
Hi @mwz 

The object com.sagacify.sonar.scala.Measures defines some methods whose names do not conform to the scalastyele convention (_E.g. "count_classes"_), which is triggering the **com.sksamuel.scapegoat.inspections.naming.MethodNames** warning (_info_).
I suspect that those names  can not be changed because sonar call them by reflection. That's only a theory I have, I haven't checked.

So I want to know if it's safe to rename those methods or no.

**Comment by mwz** [comment]
Those functions are called from [`ScalaSensor.scala`](https://github.com/mwz/sonar-scala/blob/master/src/main/scala/com/sagacify/sonar/scala/ScalaSensor.scala) and yes we should definitely update them to conform to the naming conventions.

**Comment by BalmungSan** [comment]
Roger, I will update them tomorrow.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________
