### ISSUE TITLE
[Docs] Wrong property in samples maven multi module sample

### ISSUE THREAD

**Issue by LvffY** [mwz/sonar-scala#213]
In the past few days, I was trying to set up your plugin for a scala multi module project with maven.

I set up exactly like you describe it in your [samples](https://github.com/mwz/sonar-scala/tree/master/examples/mvn/multi-module) and in particular your parent *pom.xml*. Everything worked as expected except for code coverage (with Scoverage)

Then I found the official [SonarQube documentation](https://docs.sonarqube.org/display/PLUG/Scala+Coverage+Results+Import) and when I change in your [example pom](https://github.com/mwz/sonar-scala/blob/master/examples/mvn/multi-module/pom.xml) this line :
```xml
<sonar.scala.scoverage.reportPath>${project.build.directory}/scoverage.xml</sonar.scala.scoverage.reportPath>
```

By this one
```xml
<sonar.scala.coverage.reportPaths>${project.build.directory}/scoverage.xml</sonar.scala.coverage.reportPaths>
```

After that, I got my code coverage.
I think this is a mistake in your docs but I could be wrong ... Please tell me what you think. If you think it's a mistake, I could make a pull request to fix it.

**Comment by BalmungSan** [comment]
It is not a mistake, but a confusion.

The property we have in our examples is for this _unofficial_ plugin - **sonar-scala** - which has its own `Scoverage` module.

Now, the other property, as you said, is for the _official_ SonarQube plugin - **SonarScala** - which also includes its own `Scoverage` integration.

Both plugins do not play well together. It is up to you to decide which one to use.
In #179 you will find a detailed discussion about the differences between both written by @mwz.

**Comment by mwz** [comment]
Thanks, @BalmungSan!
