### ISSUE TITLE
Refactor the class DirOrFile

### ISSUE THREAD

**Issue by BalmungSan** [mwz/sonar-scala#23]
The **DirOrFile** class located in the [_XmlScoverageReportConstructingParser.scala_](https://github.com/mwz/sonar-scala/blob/master/src/main/scala/com/buransky/plugins/scoverage/xml/XmlScoverageReportConstructingParser.scala) file should be refactored to either be fully immutable or not being a case class.

Also the class has the following associated warning: "The outer reference in this type test cannot be checked at run time." that should be addressed. I think that after refactoring the class this warning should disappear.

**Comment by mwz** [comment]
Yes, I have noticed that the scoverage plugin abuses mutable state in various places - we should definitely refactor this.
