### ISSUE TITLE
sonar-scala with ScalaStyle + Scapegoat on remote SonarQUBE server via gradle

### ISSUE THREAD

**Issue by ashok-seshadri** [mwz/sonar-scala#255]
In the documentation you have mentioned that this plugin needs to be downloaded and extracted into the SONARQUBE installation plugins directory.

Is there any way I can use this plugin without having to install it in the SONARQUBE server, by importing the plugin in my build.gradle and publishing the reports into SONAR.

Just like gradle-scoverage. In this we just add the gradle-scoverage dependency and say 
apply plugin: org.scoverage. The resulting reports are then uploaded into SONARQUBE "sonar.scala.scoverage.reportPath" property.

**Comment by mwz** [comment]
Unfortunately, SonarSource (the company behind SonarQube) didn't accept this plugin into the marketplace as they don't want to promote community plugins which are competing with their own. I've provided docker images [here](https://github.com/mwz/sonar-scala-docker) to make it easier to use this plugin, but if you don't have access to the server and you can't manage your own instance, then the alternatives are to use the [SonarScala](https://www.sonarsource.com/products/codeanalyzers/sonarscala.html) plugin which is available in [SonarCloud](https://sonarcloud.io) or can be installer via the Marketplace in your own SonarQube instance.
