### ISSUE TITLE
Improve test coverage!

### ISSUE THREAD

**Issue by mwz** [mwz/sonar-scala#29]

**Comment by BalmungSan** [comment]
Hi @mwz, how much do you want the Coverage to be?, We already are in 90%
And probably when we remove the old scalastyle module we will be good enough in terms of code coverage.
Unless you have some specific module/classes you want to increase the coverage, I think we could close this.

**Comment by mwz** [comment]
Yeah, we tend to have good coverage on any new code, so I'm happy to close this now 👍
