### ISSUE TITLE
Sonar-scala debug mode?

### ISSUE THREAD

**Issue by h-ngo** [mwz/sonar-scala#295]
Does the plugin offer a debug mode?

We enabled sonarqube debug, but doesn't seem to have much info about the plugin process. We are working on optimizing our build time. We noticed that the sonarqube scan takes more than 20mins to complete.

It always got stuck for a long while after outputting:
[sonar-scala-scoverage] The file "...." has no scoverage information ...
[sonar-scala-scoverage] The file "...." has no scoverage information ...
.
.

Before outputting:
The following classes needed for analysis were missing:
org.scalatest.WordSpec
org.scalatest.Matchers
org.scalatest.OptionValues
.
.

I guess that's when sonar-scala performed the analysis? Also, why would it report missing classes on scalatest?

Any help would be greatly appreciated. Thanks in advance.

**Comment by mwz** [comment]
> Does the plugin offer a debug mode?

Yes, I shall make a note about this in the readme when I get the chance. You can run sonar-scala in debug mode by setting the `sonar.verbose` property to `true`, e.g. `sbt -Dsonar.verbose=true sonarScan` if you use [sbt-sonar](https://github.com/mwz/sbt-sonar).

**Comment by mwz** [comment]
@h-ngo, I added a quick note about this at the bottom of [this](https://github.com/mwz/sonar-scala#sonar-scanner-properties) section in the readme.
