### ISSUE TITLE
SonarQube crashes

### ISSUE THREAD

**Issue by QADEvops1** [mwz/sonar-scala#31]
Hello,
I downloaded the latest .jar and added it to the extensions/plugins folder. When I restarted the SonarQube it fails to load.

Please help.

SonarQube version -  6.7.1 (build 35068)

when this .jar is removed from extensions/plugins folder, Sonar works fine.

**Comment by BalmungSan** [comment]
Hello @QADEvops1 
Could you paste the output from the logs/sonar.log file ?

**Comment by mwz** [comment]
Yes, I'm afraid that without seeing the logs we won't be able to help you much.

**Comment by QADEvops1** [comment]
Hi,
Please see the log below... Hope this helps.

Wrapper Started as Daemon
Launching a JVM...
Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
  Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.

2018.03.01 12:28:03 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonar/temp
2018.03.01 12:28:04 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2018.03.01 12:28:04 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonar/elasticsearch]: /opt/sonar/elasticsearch/bin/elasticsearch -Epath.conf=/opt/sonar/temp/conf/es
2018.03.01 12:28:04 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2018.03.01 12:28:05 INFO  app[][o.e.p.PluginsService] no modules loaded
2018.03.01 12:28:05 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2018.03.01 12:28:27 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
2018.03.01 12:28:27 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/opt/sonar]: /usr/java/jdk1.8.0_144/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonar/temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -cp ./lib/common/*:./lib/server/*:/opt/sonar/lib/jdbc/postgresql/postgresql-42.1.4.jar org.sonar.server.app.WebServer /opt/sonar/temp/sq-process1058687424328660590properties
2018.03.01 12:29:22 INFO  app[][o.s.a.SchedulerImpl] Process[web] is up
2018.03.01 12:29:22 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='ce', ipcIndex=3, logFilenamePrefix=ce]] from [/opt/sonar]: /usr/java/jdk1.8.0_144/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonar/temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -cp ./lib/common/*:./lib/server/*:./lib/ce/*:/opt/sonar/lib/jdbc/postgresql/postgresql-42.1.4.jar org.sonar.ce.app.CeServer /opt/sonar/temp/sq-process6043708482710990492properties
2018.03.01 12:29:41 INFO  app[][o.s.a.SchedulerImpl] Process[ce] is up
2018.03.01 12:29:41 INFO  app[][o.s.a.SchedulerImpl] SonarQube is up
2018.03.01 12:30:13 INFO  app[][o.s.a.SchedulerImpl] Process [ce] is stopped
2018.03.01 12:30:16 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
2018.03.01 12:30:16 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143
2018.03.01 12:30:16 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
2018.03.01 12:30:16 INFO  app[][o.s.a.SchedulerImpl] SonarQube is restarting
2018.03.01 12:30:16 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143
2018.03.01 12:30:16 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonar/temp
2018.03.01 12:30:16 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2018.03.01 12:30:16 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonar/elasticsearch]: /opt/sonar/elasticsearch/bin/elasticsearch -Epath.conf=/opt/sonar/temp/conf/es
2018.03.01 12:30:16 INFO  app[][o.e.p.PluginsService] no modules loaded
2018.03.01 12:30:16 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2018.03.01 12:30:39 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
2018.03.01 12:30:39 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/opt/sonar]: /usr/java/jdk1.8.0_144/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonar/temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -cp ./lib/common/*:./lib/server/*:/opt/sonar/lib/jdbc/postgresql/postgresql-42.1.4.jar org.sonar.server.app.WebServer /opt/sonar/temp/sq-process6620747621595932107properties
2018.03.01 12:31:14 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
2018.03.01 12:31:22 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
2018.03.01 12:31:22 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143
2018.03.01 12:31:22 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
<-- Wrapper Stopped
-->

**Comment by BalmungSan** [comment]
Uhm...

This is very very strange; it is saying that the es process (Elasticsearch) exited abruptly, and that’s the reason why sonar is crashing. But the point is that this plugins should not affect Elasticsearch in any way…

But this is the second time the same problem is happening, see Sagacify/sonar-scala#24

So, we really need to look at this (@mwz )

Could you please paste the output of the _logs/es.log_ file ? 

**PS:** I have a feeling that the problem could be related to no enough memory…
Could you also give us the specifications of the machine where you’re running sonar?, specially available ram.

**Comment by QADEvops1** [comment]
Hi,
The following actions resolved it:
1. Increased the vm.max_map_count to 262144 (based on Sonarqube docs)
2. Increased the open file limit for sonar user to 65536 (this message appeared after restart with first change)
3. Increased the memlock limit for sonar user to unlimited (Sonarqube docs recommendation)
4. Removed the scoverage plugin based on this message after restart with second and third changes:
Metric [scoverage] is already defined by the repository [com.buransky.plugins.scoverage.measure.ScalaMetrics@16b3f41]
5. Restarted Sonarqube with the sonar-scala plugin in the downloads folder and it is working now.

**Comment by BalmungSan** [comment]
Hello @QADEvops1,

I'm very happy to hear that you were able to solve the problem. 😄 

But it still bothers me that the plugin is making **ES** fail sometimes, maybe the plugin is using ES and we don't know (_or at least I don't_)

In any case @mwz, I think You should add those steps in the **README**, maybe as minimal recommended setup, or as a common problem resolution section.

**Comment by mwz** [comment]
It would be good to try to replicate this issue and have a look at the es logs.
@QADEvops1, would you be keen to make a contribution to the README and describe the setup recommended in the SonarQube docs?

**Comment by QADEvops1** [comment]
@mwz Not sure whether this issue is happening to everyone.  Also, Sonar setup varies based on the version.

**Comment by mwz** [comment]
I'm wondering whether the issue had nothing to do with the `with vm.max_map_count` and `fs.file-max` limits, but was actually caused by having the standalone scoverage plugin installed alongside sonar-scala...
