### ISSUE TITLE
Issues with code duplication

### ISSUE THREAD

**Issue by Nyshu** [mwz/sonar-scala#33]
Is there some way to get code duplication also working???

**Comment by mwz** [comment]
Hi @Nyshu, we currently don't support any code duplication metrics, but it's definitely on the list of features I'd like to support in this plugin. You can keep an eye on https://github.com/mwz/sonar-scala/issues/9 to track the progress.

**Comment by Nyshu** [comment]
Thanks! otherwise we have been using the plugin.
