### ISSUE TITLE
Change the Scoverage report key

### ISSUE THREAD

**Issue by BalmungSan** [mwz/sonar-scala#36]
As discussed in #34, we should add support for the new Key (`sonar.scala.scoverage.reportPath`) while maintaining the support for the old one (`sonar.scoverage.reportPath`) but adding a deprecation warning, and finally drop the support for the old one when addressing #11.

**Comment by mwz** [comment]
We should also update README to reflect the new property name.

**Comment by BalmungSan** [comment]
@mwz, would you update the README, or do you want me to do it ?, if so I will raise a PR tomorrow.

**Comment by mwz** [comment]
Sure if you have the time that would be great, otherwise I'm happy to update the README myself.

**Comment by BalmungSan** [comment]
I think it's better if you do it, for two reasons.
First you can push it directly to master, second your English is way better than mine, so i t would be cleaner.

**Comment by mwz** [comment]
I've updated README with the new property name and added a deprecation note in the [6.2.0](https://github.com/mwz/sonar-scala/releases/tag/v6.2.0) release notes.
