### ISSUE TITLE
Support PR decoration for github enterprise

### ISSUE THREAD

**Issue by jinwoo-k** [mwz/sonar-scala#414]
The company I work for is using GitHub Enterprise.
sonar-scala can only use github.com so i can't use in-house github.
If this part is modified, it seems that more users can use it.

**Comment by mwz** [comment]
Hi @jinwoo-k, thanks for the request 👍 

I'm not that familiar with GH Enterprise, so I was wondering whether the only thing that's different from GitHub is the custom URL to your installation or are there actually any API changes that we would need to make?

Unfortunately, this isn't something that's currently on my roadmap, but I'd be happy to accept contributions.

**Comment by jinwoo-k** [comment]
Thank you for your reply.
The github url of our company is https://github.companydomain.com/api/v3, and is only using URL without any problems.
So I added an apiurl variable to the Github object of GlobalConfig and was used as cli.

This is part of the GlobalConfig class I modified.
<img width="1043" alt="스크린샷 2020-04-07 오후 3 23 20" src="https://user-images.githubusercontent.com/24490553/78636904-3f69db00-78e4-11ea-91c6-306c26562e28.png">


Thank you!

**Comment by mwz** [comment]
Sounds like an easy one, would you perhaps like to open a PR for it? 😄

**Comment by jinwoo-k** [comment]
I want to. But I think I don't have the authority. Can you grant me an authority?

**Comment by mwz** [comment]
Fork the repo and you should be good to go :+1
