### ISSUE TITLE
Filename mismatch in scoverage.xml vs. what ScoverageSensor.getModuleSourceFiles() returns

### ISSUE THREAD

**Issue by coltrey** [mwz/sonar-scala#51]
In my project, ScoverageSensor.getModuleSourceFiles() includes "src/main/scala" and filename attributes in scoverage.xml do not.  This means that ScoverageSensor reports that there is no coverage information for all files.

Is there a configuration I'm missing to strip or add this part of the path from the reporting?

I'm running through maven with the sonar maven plugin.

**Comment by BalmungSan** [comment]
Hello @coltrey, the plugin should add a **prefix** to all files in the report automatically (as you can see [here](https://github.com/mwz/sonar-scala/blob/ec6915781d1de19f37a7d73162463ef654cc9e62/src/main/scala/com/mwz/sonar/scala/scoverage/ScoverageReportParser.scala#L34)), this prefix comes from the `sonar.sources` property (as you can see [here](https://github.com/mwz/sonar-scala/blob/ec6915781d1de19f37a7d73162463ef654cc9e62/src/main/scala/com/mwz/sonar/scala/scoverage/ScoverageSensor.scala#L58) and [here](https://github.com/mwz/sonar-scala/blob/ec6915781d1de19f37a7d73162463ef654cc9e62/src/main/scala/com/mwz/sonar/scala/ScalaPlugin.scala#L56)) which in the rare case that the property does not exist (because it is mandatory for sonar, at least for now), it should be defaulted to _"src/main/scala/"_.

I had to admit that I had never tested the plugin using **mvn**, but it should work the same.

Could you execute the scanner in debug mode and paste the log?, or provide a sample repo to reproduce the problem?
I will look into it **ASAP**.

**Comment by coltrey** [comment]
@BalmungSan , thank you for the help.

I think the adding of the prefix is the problem.  The filenames in scoverage.xml are like this:
`				<class 
                name="com.coltrey.SomeClass" filename="com/coltrey/SomeClass.scala" statement-count="120" statements-invoked="61" statement-rate="50.83" branch-rate="100.00">
`

I get error output like [https://github.com/mwz/sonar-scala/blob/ec6915781d1de19f37a7d73162463ef654cc9e62/src/main/scala/com/mwz/sonar/scala/scoverage/ScoverageSensor.scala#L86](this): "[scoverage] The file: 'src/main/scala/com/coltrey/SomeClass.scala', has no scoverage information associated to it."


I'll see about running in debug mode or making a reproducible repo.  I think the problem is that [https://github.com/mwz/sonar-scala/blob/ec6915781d1de19f37a7d73162463ef654cc9e62/src/main/scala/com/mwz/sonar/scala/scoverage/ScoverageSensor.scala#L71](here), because the value of "filename" passed to get() is "src/main/scala/com/coltrey/SomeClass.scala", and the key in the filesCoverable map is "com/coltrey/SomeClass.scala" it returns null.

**Comment by BalmungSan** [comment]
> because the value of "filename" passed to get() is "src/main/scala/com/coltrey/SomeClass.scala", and the key in the filesCoverable map is "com/coltrey/SomeClass.scala" it returns null.

The filename value comes from sonar (we don't create or modify it), and as you see, it comes with the prefix _"src/main/scala/"_, the map is the one we create, and the values in the map are the ones that have the prefix we add. And we add them precisely because sonar return the fienames with that prefix.

So, the problem here is that you're getting an empty prefix during the scan... that's very weird.
Do you have the `sonar.sources` property properly set?, it should be _"src/main/scala"_, maybe you have it empty?

**Comment by coltrey** [comment]
I see what you're saying... We are setting sonar.sources:
`		<sonar.sources>src/main/scala,src/main/java</sonar.sources>
`

**Comment by BalmungSan** [comment]
Uhm... probably it is failing because the property had more than one value.
I'll test it, and if that is the real cause of the bug, we should start looking for a fix.

**Comment by coltrey** [comment]
Our developer tried with just 'src/main/scala' specified in sonar.sources and received the same errors.
`The file: 'src/main/scala/com/coltrey/SomeClass.scala', has no scoverage information associated to it.`

**Comment by coltrey** [comment]
All files and they are in the scoverage.xml

We also tried with "src/main/scala/" to see if the path separator mattered and it did not work either.

**Comment by BalmungSan** [comment]
Ok, for now I had no idea what is going on.
I need a sample repo or something to reproduce and debug the problem by myself.

Probably only the relevant parts of the `pom.xml` file, and the `sonar-project.properties` file (if any).

**Comment by BalmungSan** [comment]
Without modifying the code not really, but if you can, you could just add the following line in the **ScoverageSensor.scala** file

```scala
    Try(scoverageReportParser.parse(reportFilename, sourcesPrefix)) match {
      case Success(moduleCoverage) => {
        logger.info(moduleCoverage.filesCoverage.toString) //this one
        logger.info(s"[scoverage] Successfully loaded the scoverage report file: '${reportFilename}'")
```
Then execute the following command to generate the new JAR.

```shell
$ sbt assembly
```
And finally replace the old plugin JAR with this one.

**Note:** @mwz we probably should add something similar but in debug level instead, what do you think?

**Comment by BalmungSan** [comment]
😲 
Ok, this is getting weirder every time.
I had no idea why the Map would have full paths.
I really need something to debug.

**Comment by coltrey** [comment]
I'll see if I can get this down to a hello-world type repo for you.  It will probably be Monday at the earliest.

**Comment by mwz** [comment]
Hi @coltrey and thanks for reporting this issue.
To be honest, maven has never been our focus for sonar-scala, but it looks like we should be able to fix this relatively easily and get you going with the plugin.
If you are able to share with us a sample project so we could replicate this issue that would be great 👍

**Comment by coltrey** [comment]
@BalmungSan @mwz [https://github.com/coltrey/sonar-scala-scantest](This repo) shows the same coverage not found error for me.

**Comment by mwz** [comment]
Excellent, thank you @coltrey - I should be able to have a look in the evening and hopefully we can get to the bottom of this and get this 🐛squashed!

**Comment by BalmungSan** [comment]
Hi @coltrey & @mwz, I'll take a quick look right now. Let's see what I can find.

**Comment by coltrey** [comment]
@BalmungSan Thank you.  Should be as easy as "mvn clean build sonar:sonar" after you set the sonar.login and sonar.host.url in pom.xml

`
		<sonar.login>SONAR_LOGIN_KEY</sonar.login>
		<sonar.host.url>SONAR_URL</sonar.host.url>
`

**Comment by BalmungSan** [comment]
Hello @coltrey, Yes. I already take a look at it and I found that the mvn plugin makes the `sonar.sources` property full path, that's why it is failing.

For now I have no idea how to overcome this bug, so I will wait if @mwz finds something else.

But a temporary workaround to problem while we fix it, would be to use the _sonar-scanner_ shell utility, instead of the maven plugin.

**Comment by coltrey** [comment]
I'll start testing with sonar-scanner during our CI process as a workaround.  Since this is a hybrid java/scala project, I'm not sure how that will complicate things for me.

Aside from a configuration toggle, there's probably not a way for the maven plugin maintainers to change behavior that without breaking compatibility.

As for this project,

- If you can detect that the scan is running from inside the maven scanner plugin, you could assume absolute paths.  There's probably a downside to making that kind of assumption.
- You can check to see if the key inside filesCoverage is an absolute path (convert to a java.nio.Path object and call .isAbsolute()), then if it does assume absolute paths and convert the lookups appropriately.  I haven't been able to think of a downside to this, unless I'm misunderstanding the isAbsolute() method.

**Comment by mwz** [comment]
Relativization of the absolute path should be just enough to handle the way maven plugin populates the `sonar.sources` property and I have a working fix for that, but before I open a PR I want to test sbt projects using sonar-scanner and multi-module projects to make sure we don't introduce more issues, so bear with me on that.

While we're at it, I think, we can also address the other issue related to handling multiple source prefixes, but I'm not yet entirely sure what the best way to deal with those is, so I'll sleep on it and I'll see what I can come up with tomorrow.

**Comment by coltrey** [comment]
@mwz do you think your fix for relativation will solve the windows pathing as well?

**Comment by mwz** [comment]
It should in theory, however, I don't use Windows so it might be difficult for me to test this.

It's easy enough these days to run things in docker containers, even on [Windows](https://www.docker.com/docker-windows-server) (see https://hub.docker.com/_/sonarqube, https://github.com/mwz/sonar-scala-docker), so we've not really been making any extra effort to make sure things work on Windows.

**Comment by coltrey** [comment]
I'll test windows Monday morning and have our dev test after that.  Thank you.

**Comment by mwz** [comment]
@coltrey, would you mind checking for me if the paths in your scoverage report use `\` or `/`?

**Comment by coltrey** [comment]
They are backslashes.
```
                <class
                name="com.coltrey.ScalaSonar.ScalaSonar" filename="com\coltrey\ScalaSonar\ScalaSonar.scala" statement-count="1" statements-invoked="0" statement-rate="0.00" branch-rate="0.00">
                    <methods>
                        <method
                        name="com.coltrey.ScalaSonar/ScalaSonar/main" statement-count="1" statements-invoked="0" statement-rate="0.00" branch-rate="0.00">
                            <statements>
                                <statement
                                package="com.coltrey.ScalaSonar" class="ScalaSonar" class-type="Object" full-class-name="com.coltrey.ScalaSonar.ScalaSonar" source="C:\Users\coltrey\workspace\sonar-scala-scantest\src\main\scala\com\coltrey\ScalaSonar\ScalaSonar.scala" method="main" start="102" end="126" line="5" branch="false" invocation-count="0" ignored="false">
</statement>
                            </statements>
</method>
                    </methods>
</class>
```

**Comment by mwz** [comment]
Perhaps you should try setting your `sonar.sources` property to `src\main\scala` instead of `src/main/scala`?

**Comment by coltrey** [comment]
Wouldn't that then break the unix side?

**Comment by mwz** [comment]
Well, I think that the `sonar.sources` path needs to be specific to the OS which you use to scan your project and generate a scoverage report. Since the paths in your scoverage report have backslashes, you probably should be consistent and use `\` in your `sonar.sources` too.

**Comment by coltrey** [comment]
FYI: one of our devs tested this build on his Mac and it worked great.  Thank you for looking into it and for the quick fix.  I'm happy to close this issue now, because the windows vs. unix pathing isn't very important to me.

That said, setting sonar.sources to `src\main\scala` produces the same output.  I don't think that's a very good fix anyway - asking people who work in heterogenous dev environments to modify a pom to build doesn't seem like a good pattern to me.  I'm also not sure if this is something that should be fixed in this project or in scoverage...
```
[DEBUG] 11:48:10.118 [scoverage] ModuleCoverage(Scoverage(1,0,0.0,0.0),Map(src\main\scala\com\coltrey\ScalaSonar\ScalaSonar.scala -> FileCoverage(Scoverage(1,0,0.0,0.0),Map(5 -> 0))))
[WARNING] 11:48:10.118 [scoverage] The file: 'src/main/scala/com/coltrey/ScalaSonar/ScalaSonar.scala' has no scoverage information associated with it.
```
