### ISSUE TITLE
Releases does not include built artifact

### ISSUE THREAD

**Issue by dwlocks** [mwz/sonar-scala#74]
The README.md states there should be an artifact on the github releases page.  There is not.  

So either the README.md is out of date, or the CI system is not correctly uploading all your files.

(I opened a pull request giving basic build instructions in case you don't want to provide downloadable jars)

**Comment by mwz** [comment]
Hi @dwlocks, the artifacts are hosted on Bintray and you can download them by wither clicking on the version badge or going to the releases page - there is a link to the artifact at the bottom of each release note:

![badge](https://user-images.githubusercontent.com/1190768/41808180-b872205a-76d1-11e8-924d-c82337217f4f.png)

![release-notes](https://user-images.githubusercontent.com/1190768/41808184-bdbd9bfc-76d1-11e8-871e-f21a8e1d6726.png)
