### ISSUE TITLE
Create a project microsite

### ISSUE THREAD

**Issue by mwz** [mwz/sonar-scala#78]
It would be good to have a microsite with detailed instructions on how to set everything up, how to use and configure the plugin, how to set up quality profiles with sonar-scala rules etc.

**Comment by mwz** [comment]
Hey @BalmungSan, I've started creating a microsite for this project.

There is just a landing site for now, but I'm planning to move and refine all the content from the readme and add some more useful info in there.

Let me know if you have any comments so far, any feedback would be much appreciated.

https://sonar-scala.com

You can find the repo [here](https://github.com/sonar-scala/website) if you're interested to see how it's built. I've decided to give the new Docusaurus a try. Even though it's still in alpha, it's already pretty stable - https://v2.docusaurus.io.

**Comment by BalmungSan** [comment]
@mwz Amazing work!

Just two things:

1. Add the link, here, in the description of the project _(but maybe you are just waiting until the site is complete)_.
2. I would put the images down the tittle, instead of the tittle down the image.

**Comment by mwz** [comment]
Thanks for having a look 👍 

> 2\. I would put the images down the tittle, instead of the tittle down the image.

I've made the change, does it look any better now?
