### ISSUE TITLE
Set up sonar-scala recommended quality profile

### ISSUE THREAD

**Issue by mwz** [mwz/sonar-scala#80]
Here is a list of Scapegoat and Scalastyle rules that we disabled or changed the severity for in the public SonarQube [instance](https://sonar.sonar-scala.com/coding_rules#activation=true|qprofile=AWGxRb3wcfvDQuD_lsPk|languages=scala), so we could use it as a reference.

disabled:
- `common-scala:InsufficientCommentDensity` - Source files should have a sufficient density of comment lines
- `scapegoat:com.sksamuel.scapegoat.inspections.unneccesary.UnnecessaryReturnUse` - Checks for use of \`return\` keyword in blocks
- `scapegoat:com.sksamuel.scapegoat.inspections.imports.WildcardImport` - Checks for wildcard imports
- ~`scapegoat:com.sksamuel.scapegoat.inspections.RedundantFinalModifierOnCaseClass` - Redundant final modifier on case class~ - update: does not exist in the latest version of Scapegoat 
- `Scalastyle:scalastyle_BlockImportChecker` - Avoid block imports
- `Scalastyle:scalastyle_UnderscoreImportChecker` - Avoid wildcard imports
- `Scalastyle:scalastyle_LowercasePatternMatchChecker` - Lowercase pattern match
- `Scalastyle:scalastyle_NoNewLineAtEofChecker` - No Newline at EOF
- `Scalastyle:scalastyle_PatternMatchAlignChecker` - Pattern match align

changed severity:
- `Scalastyle:scalastyle_SpaceAfterCommentStartChecker` - MINOR - Space after the start of the comment

This list doesn't include any changes to Scalastyle templates, but we'll update it once we review those as a part of #35.

**Comment by BalmungSan** [comment]
Given we want to be flexible enough to decide which rules we want, their severity and even override their parameters... I think first of all we should define how we would like to configure it.

In my opinion it would be better to define the properties of the profile in an structured file like xml, and then process it in code to generate the profile. I would even believe that if would be best if we generate the profile code in the meta project; but we can discuss that later.

Now, I'm more interested in defining the structure of the profile definition file, I see two options: One is to define all rules we want, with the severity we want and the parameter we want to override. The second one is to define only the ones we would like to exclude, the ones we would like to change the severity and the ones we would like to create from the templates, including all others as they are.

**Comment by mwz** [comment]
> Given we want to be flexible enough to decide which rules we want, their severity and even override their parameters... I think first of all we should define how we would like to configure it.

Yeah, that sounds like a good first step.

> In my opinion it would be better to define the properties of the profile in an structured file like xml, and then process it in code to generate the profile. I would even believe that if would be best if we generate the profile code in the meta project; but we can discuss that later.

I think we should just define the config somewhere in the code - it will save us the hassle of having to load and process the xml file. There's probably no need for it to come from an external file sice it will be only used internally.

> Now, I'm more interested in defining the structure of the profile definition file, I see two options: One is to define all rules we want, with the severity we want and the parameter we want to override. The second one is to define only the ones we would like to exclude, the ones we would like to change the severity and the ones we would like to create from the templates, including all others as they are.

I haven't thought too much about it yet, but at first glance, it looks like we'll mostly want to:

1. Blacklist some rules from the quality profile - I think this could be as simple as a set of rule keys that we don't want to include in the profile. It can be probably shared between Scalastyle and Scapegoat.

2. Override the severity of some rules - this could be a map of rule keys to new severity for the rules that we want to override, e.g. `Map[String, Severity]`.

3. Instantiate new Scalastyle templates - We'll need to review the templates and decide which ones make sense to keep with default values and which once we want to instantiate with different values. Those default template instances from the Scalastyle repository that we want to blacklist can be excluded using the mechanism from 1. I think that a map will also be ok in this case - we'll want to capture the template (rule) id that we want to instantiate, a rule key which will be used to create this new instance, a map with parameter key/values and the severity. Here is what it might look like:
   ```scala
   type Templates = Map[String, Template]
   case class Template(ruleId: String, newRuleKey: String, params: Map[String, String], severity: Severity)
   ```

**Comment by mwz** [comment]
Ok, I'll have a go at this.
