### ISSUE TITLE
Add Scapegoat to example projects

### ISSUE THREAD

**Issue by mwz** [mwz/sonar-scala#82]
This probably only applies to the sbt projects, although it might be possible to get it also working with Maven. I'm not sure if there is a way to run Scapegoat with Gradle projects.

**Comment by BalmungSan** [comment]
Well the official Scapegoat repo provides [instructions for integration with maven](https://github.com/sksamuel/scapegoat#maven).

Regarding gradle, I have no idea, but I found [this](https://gist.github.com/fomkin/9eeae63f4750da8443e86a643803cba7), a gist for configuring a compiler module in gradle.
And [this](http://central.maven.org/maven2/io/jenner/gradle-scapegoat/0.90.0/), an old _(and probably dead)_ scapegoat-gradle plugin, but I couldn't find the source or documentation anywhere.
