### ISSUE TITLE
Compatibility check with Sonar 9.2

### ISSUE THREAD

**Issue by shafemoh** [mwz/sonar-scala#834]
Hi team,

This request is an extension to https://github.com/sonar-scala/sonar-scala/issues/786
We saw that this plugin has now an official support for Sonarqbue 9.4 but we are currently running Sonarqube on version 9.2. Does this plugin support Sonarqube 9.2 (obviously it shouldn't, but my question still)?

However, when we installed the latest one (supported for 9.4) on Sonarqube 9.2, it broke the application with 502 BadGateway with the following errors, which is quite obvious.

_2022.05.11 11:50:48 DEBUG web[][o.p.ssl.MakeSSL] converting regular socket connection to ssl
2022.05.11 11:50:48 ERROR web[][o.s.s.p.PlatformImpl] **Web server startup failed: Plugin Scala [scala] requires at least SonarQube 9.4.0.54424**
2022.05.11 11:50:48 DEBUG web[][o.a.h.i.n.c.PoolingNHttpClientConnectionManager] Connection manager is shutting down
2022.05.11 11:50:48 DEBUG web[][o.a.h.i.n.c.PoolingNHttpClientConnectionManager] Connection manager shut down
2022.05.11 11:50:49 DEBUG web[][o.s.s.a.TomcatAccessLog] Tomcat is started
2022.05.11 11:50:49 INFO web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2022.05.11 11:50:49 INFO web[][o.s.p.ProcessEntryPoint] Hard stopping process
2022.05.11 11:50:49 DEBUG web[][o.s.s.a.TomcatAccessLog] Tomcat is stopped
(END)_

So...
1. Will this plugin be released specifically for 9.2 support? If yes, then we will just use it straight away
2. Other way around, we have to upgrade Sonarqube to 9.4 just for this purpose :slightly_smiling_face:

_Note: We tried installing the plugin that was compatible with 8.9.0 and it worked without any issues_

**Comment by mwz** [comment]
The latest release is built against SonarQube 9.4 and won't work with earlier versions.
There's no new features in the latest sonar-scala version, so If 8.9.0 works for you then great - you should continue using it, but I'd suggest updating to sonar-scala 9.0.0 when you upgrade SonarQube to 9.4.
