### ISSUE TITLE
What is sonar-scala-assembly.jar?

### ISSUE THREAD

**Issue by shafemoh** [mwz/sonar-scala#839]
Hi team,
we would like to use your plugin for our Sonarqube EE (9.4.0) application. We would like to use the [v9.0.0](https://github.com/sonar-scala/sonar-scala/releases/tag/v9.0.0) of this plugin sonar-scala.

However when I look at the [releases page](https://github.com/sonar-scala/sonar-scala/releases), I see it's written: _This plugin is available for download from [Sonatype](https://s01.oss.sonatype.org/content/repositories/releases/com/sonar-scala/sonar-scala_2.13/9.0.0/sonar-scala_2.13-9.0.0-assembly.jar)._ This is letting us download an assembly jar  (**_sonar-scala_2.13-9.0.0-assembly.jar_**).

is an assembly jar an official sonar-scala plugin jar? OR do you have any other specific named release like **_sonar-scala_2.13-9.0.0.jar_** instead of **_sonar-scala_2.13-9.0.0-assembly.jar_**?

**Comment by mwz** [comment]
Hi, yes - the assembly file is the jar you should be using to install sonar-scala.
