### ISSUE TITLE
Display the number of unit tests

### ISSUE THREAD

**Issue by h-ngo** [mwz/sonar-scala#91]
Is it true that this plug in doesn't display the number of unit tests?

We can't find it anywhere in the sample project: https://sonar.sonar-scala.com/dashboard?id=gradle-multi-module. Nor in our project.

This was how the overview page looked with the previous sonar scala plugin that we used
![image](https://user-images.githubusercontent.com/34242287/42839461-c9cc19ce-89d1-11e8-99ee-0aab7c61c246.png)

The Measures tab also gave us a report on how many tests were in each Spec file.

**Comment by h-ngo** [comment]
nvm. Just noticed that this question was previously asked by another user, and it's currently on to-do list
https://github.com/mwz/sonar-scala/issues/32

**Comment by mwz** [comment]
Hi @h-ngo - thanks for expressing your interest in this feature. It's not super high on my priority list, but yeah, we can definitely prioritise this over some other things as there seems to be some interest in this feature. Obviously, we would happily accept a PR if that's something you would be keen to contribute? 😄
