### ISSUE TITLE
SonarQube crashes

### ISSUE THREAD

**Issue by josefarinna** [mwz/sonar-scala#93]
Hello,

This morning I just updated a plugin from the Market and after restart the sonar instance I'm not able to make it run again, I checked the logs and in the web.log there is a crash related with the scala plugin. other log files looks good. After removing the updated plugin, sonar is still failing, I removed sonar-scala and now it boots without issue. I'm running sonarqube on a Windows machine.

Any suggestion?

Thanks!

[web.log](https://github.com/mwz/sonar-scala/files/2244538/web.log)

**Comment by mwz** [comment]
Hi @josefarinna, would you be able to share some more details with us, e.g. which plugin you updated from the Marketplace and, most importantly, which version of SonarQube you're running?

**Comment by josefarinna** [comment]
I updated SonarCss from 1.0.0 to 1.0.1, but as I thought it could be the issue, I removed it completely, but still not working. I'm running SonarQube 7.2.1

**Comment by mwz** [comment]
That's your issue then, sonar-scala currently supports only the 6.7 LTS series.

**Comment by josefarinna** [comment]
It was working fine before updating that plugin, I guess I'll wait until the plugin oficially supports the current version.

Thanks!
