### ISSUE TITLE
Releases URL doesn't have jars

### ISSUE THREAD

**Issue by EslamElHusseiny** [mwz/sonar-scala#94]
Hi,
releases URL in the README https://github.com/mwz/sonar-scala/releases doesn't have links to jars.
I found them in https://dl.bintray.com/mwz/maven/com/github/mwz/sonar-scala_2.12/ instead.

**Comment by BalmungSan** [comment]
Duplicate of #74

**Comment by EslamElHusseiny** [comment]
Thanks @BalmungSan
